# TODO: should not import
Import("test_env")

test_env.Program("simple_packet_transfer",
		["simple_packet_transfer.cpp"],
		LIBS = ["framework_network", "basic", "event", "framework_threads", "pthread", "packets", "log4cxx"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)

test_env.Program("queue_packet_transfer",
		["queue_packet_transfer.cpp", "PacketHandlerFactory.cpp"],
		LIBS = ["framework_network", "basic", "event", "framework_threads", "pthread", "packets", "log4cxx"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)
		