# TODO: should not import
Import("test_env")

test_env.Program("queue_packet_transfer",
		[
		"queue_packet_transfer.cpp",
		"PacketHandlerFactory.cpp",
		"PacketTransfer.cpp",
		],
		LIBS = [
			"framework_network", "basic", "event",
			"framework_threads", "pthread", "packets",
			"log4cxx", "llpackets", "boost_thread-mt", "uuid"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)
		