# TODO: should not import
Import("env")

env.Program("simulator",
		[
		"Simulator.cpp",
		"PacketServer.cpp",
		"ClientConnection.cpp",
		],
		LIBS = [
			"framework_network", "basic", "event",
			"framework_threads", "pthread", "packets",
			"log4cxx", "llpackets", "boost_thread-mt",
			"rudp", "uuid"],
		CPPPATH = ["../Framework", "../Protocol", "../include"],
		LIBPATH = ["../lib"],
		)
		