# TODO: should not import
Import("env")

env.Program("simulator",
		[
		"Simulator.cpp",
		"PacketServer.cpp",
		"ClientConnection.cpp",
		],
		LIBS = [
			"basic", "PocoNetd", "PocoFoundationd", "rudp", "packets",
			"log4cxx", "llpackets"],
		CPPPATH = ["../Framework", "../Protocol", "../include"],
		LIBPATH = ["../lib"],
		)
		