# TODO: should not import
Import("test_env")

test_env.Program("file_transfer",
		[
		"file_transfer.cpp",
		"FileTransferNode.cpp",
		"FileTransferClientConnection.cpp",
		],
		LIBS = [
			"framework_network", "basic", "event",
			"framework_threads", "pthread", "packets",
			"log4cxx", "filetransferpackets", "boost_thread-mt",
			"packet_transfer", "uuid"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)
		