# TODO: should not import
Import("test_env")

test_env.Program(
	"../../bin/file_transfer",
	[
	"src/file_transfer.cpp",
	"src/FileTransferNode.cpp",
	"src/FileTransferClientConnection.cpp",
	],
	LIBS = [
		"PocoNetd", "PocoFoundationd", "PocoUtild", "PocoXMLd",
		"basic", "packets", "ftpackets", "rudp",
		],
	CPPPATH = [
		"include",
		"../../Basic/include",
		"../../Framework/Packets/include",
		"../../Framework/rUDP/include",
		"../../Protocol/FTPackets/include",
		],
	LIBPATH = ["../../lib"],
	)

