# TODO: should not import
Import("test_env")

test_env.Program("file_transfer",
		[
		"file_transfer.cpp",
		"FileTransferNode.cpp",
		"FileTransferClientConnection.cpp",
		],
		LIBS = [
			"PocoNetd", "PocoFoundationd", "PocoUtild", "PocoXMLd",
			"basic", "packets", "log4cxx", "filetransferpackets",
			"rudp", "uuid"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)
		