Import("env")

files = [
	"ConnectionBase.cpp",
	"TransferNode.cpp",
	"Sender.cpp",
	"Receiver.cpp",
	"PacketHandlerFactory.cpp",
	]

env.SharedLibrary("../../lib/rudp", files,
	CPPPATH =["../../include", "../../Framework"])

