# TODO: should not import
Import("test_env")

test_env.Program("test_thread_manager",
		"test_thread_manager.cpp",
		LIBS = ["framework_threads", "basic", "pthread", "log4cxx"],
		CPPPATH = ["../../Framework", "../../include"],
		LIBPATH = ["../../lib"],
		)
