Import("env")

files = [
      "src/ExceptionBase.cpp",
      "src/Exception.cpp",
      "src/ThreadManager.cpp",
      "src/ThreadWorker.cpp",
	]

env.SharedLibrary(
	"../lib/basic",
	files,
	CPPPATH = ["include", ],
	)

