Import("env")

files = [	"QueueFactory.cpp",
			"ThreadManager.cpp",
			"ThreadWorker.cpp",
			"Thread.cpp",
			"DataControl.cpp",
			]

env.SharedLibrary("../../lib/framework_threads", files, CPPPATH="../../include")
