# TODO: should not import
Import("test_env")

test_env.Program("test_timer",
		[
		"timer.cpp",
		],
		LIBS = ["basic", "framework_threads", "pthread", "log4cxx", "uuid", "boost_thread-mt"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)

test_env.Program("test_uuid",
		[
		"UUID.cpp",
		],
		LIBS = ["basic", "pthread", "log4cxx", "boost_thread-mt", "uuid"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)
