Import("env")

files = [
	"src/PacketBase.cpp",
	"src/PacketFactory.cpp",
	"src/PacketHeader.cpp",
	"src/PacketSerializer.cpp",
	"src/PacketBaseTypes.cpp",
	]

env.SharedLibrary(
	"../../lib/packets",
	files,
	CPPPATH=["include", "../../Basic/include"]
	)

