# TODO: should not import
Import("test_env")

test_env.Program("echo_server",
		["EchoServer.cpp"],
		LIBS = [
		"framework_network", "basic", "event",
		"framework_threads", "pthread", "log4cxx"],
		CPPPATH = ["../../Framework", "../../Protocol", "../../include"],
		LIBPATH = ["../../lib"],
		)

