Import("env")

files = [
	"FanniSock.cpp",
	"Event_UDP.cpp",
	]

env.SharedLibrary("../../lib/framework_network", files,
	CPPPATH =["../../include", "../../Framework"])

#
#Import("env")
#
#files = [
#	"UDPServer.cpp",
#	"IOUtils.cpp",
#	]
#
#env.SharedLibrary("../../../lib/framework_network", files,
#	CPPPATH =["../../../include", "../../../Framework"])
#
