Import("env")

files = [
	"src/ConnectionBase.cpp",
	"src/TransferNode.cpp",
	"src/Sender.cpp",
	"src/Receiver.cpp",
	"src/PacketHandlerFactory.cpp",
	]

env.SharedLibrary("../../lib/rudp", files,
	CPPPATH =["include", "../../Framework/Packets/include", "../../Basic/include"])

