# TODO: should not import
Import("test_env")

test_env.Program("test_serializer",
		"test_serializer.cpp",
		LIBS = ["packets", "basic", "log4cxx", "llpackets", "PocoFoundationd"],
		CPPPATH = ["../../Protocol", "../../include", "../../Framework"],
		LIBPATH = ["../../lib"],
		)

test_env.Program("test_serializer_basetypes",
		"test_serializer_basetypes.cpp",
		LIBS = ["packets", "basic", "log4cxx", "PocoFoundationd"],
		CPPPATH = ["../../Protocol", "../../include", "../../Framework"],
		LIBPATH = ["../../lib"],
		)

test_env.Program("test_zerocode",
		"test_zerocode.cpp",
		LIBS = ["packets", "basic", "log4cxx", "llpackets", "PocoFoundationd"],
		CPPPATH = ["../../Protocol", "../../include", "../../Framework"],
		LIBPATH = ["../../lib"],
		)

test_env.Program("test_packet",
		"test_packet.cpp",
		LIBS = ["packets", "basic", "log4cxx", "PocoFoundationd"],
		CPPPATH = ["../../Protocol", "../../include", "../../Framework"],
		LIBPATH = ["../../lib"],
		)
		